const actionTypes = Object.freeze({
   //app
   APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
   SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
   CHANGE_LANGUAGE: 'CHANGUAGE_LANGUAGE',

   //user
   ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
   USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
   USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
   PROCESS_LOGOUT: 'PROCESS_LOGOUT',

   // admin:
   //-gender
   FETCH_GENDER_START: 'FETCH_GENDER_START',
   FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
   FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

   //-Position
   FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',
   FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',

   //- Role
   FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',
   FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',

   //GetAllUsersRedux
   FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',
   FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',

   // CRUD User Redux
   CREATE_USER_FAILED: 'CREATE_USER_FAILED',
   CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',

   DELETE_USER_FAILED: 'DELETE_USER_FAILED',
   DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

   UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',
   UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',


   // get All top DOCTOR
   FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',
   FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
   // get All DOCTOR
   FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',
   FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
   // Create DOCTOR
   SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',
   SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
   // getDetail Doctor By ID
   GET_DETAIL_DOCTOR_FAILED: 'GET_DETAIL_DOCTOR_FAILED',
   GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',

   // Get TIme schedule
   FETCH_ALLCODE_SCHEDULE_TIME_FAILED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',
   FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
   //get All information doctor
   FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',
   FETCH_REQUIRED_DOCTOR_INFOR_FAILED: 'FETCH_REQUIRED_DOCTOR_INFOR_FAILED'

});

export default actionTypes;
